# Generated by Django 3.0.7 on 2020-09-02 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('phone2', models.CharField(blank=True, max_length=20, verbose_name='Additional Phone Number')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Non-Binary', 'Non-Binary')], max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_authorised',
            new_name='is_verified',
        ),
        migrations.CreateModel(
            name='AccountName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('middlenames', models.CharField(blank=True, max_length=100)),
                ('lastname', models.CharField(max_length=50)),
                ('preferred_name', models.CharField(blank=True, max_length=50)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='app.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(blank=True, max_length=30)),
                ('line2', models.CharField(blank=True, max_length=30)),
                ('suburb', models.CharField(blank=True, max_length=30)),
                ('town_city', models.CharField(blank=True, max_length=30)),
                ('postcode', models.PositiveIntegerField(blank=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='app.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='app.Gender'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL),
        ),
    ]
