# Generated by Django 3.0.7 on 2020-09-02 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200902_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='app.Gender'),
        ),
    ]
