# Generated by Django 3.0.7 on 2020-09-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200902_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountaddress',
            name='postcode',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
