# Generated by Django 3.0.7 on 2020-09-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200902_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountaddress',
            name='postcode',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
