# Generated by Django 3.0.7 on 2020-09-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200902_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temporary_date',
            field=models.DateField(null=True),
        ),
    ]
