# Generated by Django 3.0.7 on 2020-09-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200905_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
