# Generated by Django 3.0.7 on 2020-09-07 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_hub_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hub',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
